export const AppRoutes = {
  home: '/',
  login: '/login',
  register: '/register',
  bookAppointment: '/appointment',
  chatSupport: '/chat-and-support',
  overview: '/overview',
  schedule: '/schedule',
  department: '/department',
  uniqueDept: '/department/:id',
  patient: '/patient',
  uniquePatient: '/patient/:id',
  reports: '/reports',
  settings: '/settings',
  notification: '/notification',
  notFound: '*',
};
